### ISSUE TITLE
[v3] Error: Database is disconnected

### ISSUE THREAD

**Issue by nervgh** [vadimdemedes/mongorito#145]
I use mongorito `v3`;

I have a simple function:

``` js
let {body} = this.request;
console.log('body', body); // body { todoId: 198, days: 2, hours: 0, minutes: 0 }
let time = new ElapsedTime(body); // My model
console.log('time.toJSON()', time.toJSON()); // time.toJSON() { todoId: 198, days: 2, hours: 0, minutes: 0 }
let result = yield time.save(); // <--- Error here
console.log('result', result);
this.body = result;
```

```
{ Error: Database is disconnected.
    at Database.connection (/home/nerv/Projects/element-studio/time-tracking/node_modules/mongorito/lib/database.js:54:26)
    at Function.connection (/home/nerv/Projects/element-studio/time-tracking/node_modules/mongorito/lib/model.js:223:24)
    at Function.dbCollection (/home/nerv/Projects/element-studio/time-tracking/node_modules/mongorito/lib/model.js:227:15)
    at globalHooks.run.then.then (/home/nerv/Projects/element-studio/time-tracking/node_modules/mongorito/lib/model.js:106:33)
    at process._tickCallback (internal/process/next_tick.js:103:7) status: 500 }

```

**Comment by vdemedes** [comment]
Can you still reproduce it with the current master? If yes, do you mind posting a more complete code example? Thanks!

**Comment by vadimdemedes** [comment]
Closing due to inactivity.
